AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      LifecycleConfiguration:
        Rules:
        - Id: ExpireRule
          Status: Enabled
          Transition:
            TransitionInDays: 91
            StorageClass: GLACIER 
          ExpirationInDays: 2555
          AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 7
Outputs:
  BucketName:
    Value: !Ref 'LoggingBucket'
    Description: A bucket to store logs.
    Export:
      Name: LoggingBucket