AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
Outputs:
  BucketName:
    Value: !Ref 'LoggingBucket'
    Description: A bucket to store logs.
    Export:
      Name: LoggingBucket